namespace evaluacion.services;

public class CodigosError
{


    #region Códigos Error de Servicios

    #region Códigos Error de ServicioEvaluación Generales
    public const string EVALUACION_ERROR_DESCONOCIDO = "EVALUACION-ERROR-DESCONOCIDO";
    public const string EVALUACION_DATOS_NO_VALIDOS = "EVALUACION-DATOS-NO-VALIDOS";
    public const string EVALUACION_SIN_INTERPRETE_CONSULTA = "EVALUACION-SIN_INTERPRETE_CONSULTA";
    public const string EVALUACION_NO_HAY_INTERPRETE_CONSULTA = "EVALUACION-NO-HAY-INTERPRETE-CONSULTA";
    public const string EVALUACION_ESTADONUEVO_ERROR = "EVALUACION-ESTADONUEVO-ERROR";
    #endregion


    #region Códigos Error de la Entidad Evaluación  [N1]

    public const string EVALUACION_NO_ENCONTRADA = "EVALUACION-NO-ENCONTRADA";
    public const string EVALUACION_ID_PAYLOAD_NO_INGRESADO = "EVALUACION-ID-PAYLOAD-NO-INGRESADO";
    public const string EVALUACION_ID_NO_INGRESADO = "EVALUACION-ID-NO-INGRESADO";

    #region Cógidos Error de la Entidad Reactivo - TemaEvaluacion Hijo de Evaluacion [N2]
    public const string EVALUACION_REACTIVO_ACCION_NO_IMPLEMENTADA = "EVALUACION-REACTIVO-ACCION_NO_IMPLEMENTADA";
    public const string EVALUACION_REACTIVO_ERROR_INSERTAR = "EVALUACION-REACTIVO-ERROR-INSERTAR";
    public const string EVALUACION_REACTIVO_EXISTENTE_ERROR = "EVALUACION-REACTIVO-EXISTENTE-ERROR";
    public const string EVALUACION_REACTIVO_ID_PAYLOAD_NO_INGRESADO = "EVALUACION-REACTIVO-ID-PAYLOAD-NO-INGRESADO";
    public const string EVALUACION_TEMAEVALUACION_NO_ENCONTRADO = "EVALUACION-TEMAEVALUACION-NO-ENCONTRADO";
    public const string EVALUACION_REACTIVO_NO_ENCONTRADO = "EVALUACION-REACTIVO-NO-ENCONTRADO";
    public const string EVALUACION_REACTIVO_ID_NO_INGRESADO = "EVALUACION-REACTIVO-ID-NO-INGREASADO";
    #endregion

    #region Códigos Error de la Entidad VarianteEvaluacion - Hijo de la Entidad Evaluacion[N2]
    public const string EVALUACION_VARIANTEEVALUACION_EXISTENTE = "EVALUACION_VARIANTEEVALUACION_EXISTENTE";
    public const string EVALUACION_VARIANTEEVALUACION_ID_PAYLOAD_NO_INGRESADO = "EVALUACION-VARIANTEEVALUACION-ID-PAYLOAD-NO-INGRESADO";
    public const string EVALUACION_VARIANTEEVALUACION_ID_NO_INGRESADO = "EVALUACION-VARIANTEEVALUACION-ID-NO-INGRESADO";
    public const string EVALUACION_VARIANTEEVALUACION_NO_ENCONTRADA = "EVALUACION_VARIANTEEVALUACION_NO_ENCONTRADA";

    #endregion

    #endregion

    #endregion




    #region Códigos Error de Controllers


    #endregion

}
