namespace seguridad.servicios;
public class CodigosError
{
    public const string SEGURIDAD_ERROR_DESCONOCIDO = "SEGURIDAD-ERROR-DESCONOCIDO-ERROR-DESCONOCIDO";
    public const string SEGURIDAD_DATOS_NO_VALIDOS = "SEGURIDAD-ERROR-DESCONOCIDO-DATOS-NO-VALIDOS";

    public const string SEGURIDAD_APLICACIO_NO_ENCONTRADA = "SEGURIDAD-APLICACION-NO-ENCONTRADA";
    public const string SEGURIDAD_APLICACION_ID_PAYLOAD_NO_INGRESADO = "SEGURIDAD-APLICACION-ID-PAYLOAD-NO-INGRESADO";
    public const string SEGURIDAD_APLICACION_ID_NO_INGRESADO = "SEGURIDAD-APLICACION-ID-NO-INGRESADO";
    public const string SEGURIDAD_APLICACION_ERROR_ENVIO_A_CONVERSACION = "SEGURIDAD-APLICACION-ERROR-ENVIO-A-CONVERSACION";
    public const string SEGURIDAD_APLICACION_ERROR_ACTUALIZAR = "SEGURIDAD-APLICACION-ERROR-ACTUALIZAR";
    public const string CSEGURIDAD_APLICACION_ERROR_ELIMINAR = "SEGURIDAD-APLICACION-ERROR-ELIMINAR";

    public const string SEGURIDAD_GRUPOSUSUARIOS_NO_ENCONTRADA = "SEGURIDAD-GRUPOSUSUARIOS-NO-ENCONTRADA";
    public const string SEGURIDAD_GRUPOSUSUARIOS_ID_PAYLOAD_NO_INGRESADO = "SEGURIDAD-GRUPOSUSUARIOS-ID-PAYLOAD-NO-INGRESADO";
    public const string SEGURIDAD_GRUPOSUSUARIOS_ID_NO_INGRESADO = "SEGURIDAD-GRUPOSUSUARIOS-ID-NO-INGRESADO";

    public const string SEGURIDAD_INSTANCIAAPLICACION_NO_ENCONTRADA = "SEGURIDAD-INSTANCIAAPLICACION-NO-ENCONTRADA";
    public const string SEGURIDAD_INSTANCIAAPLICACION_ID_PAYLOAD_NO_INGRESADO = "SEGURIDAD-INSTANCIAAPLICACION-ID-PAYLOAD-NO-INGRESADO";
    public const string SEGURIDAD_INSTANCIAAPLICACION_ID_NO_INGRESADO = "SEGURIDAD-INSTANCIAAPLICACION-ID-NO-INGRESADO";
    public const string SEGURIDAD_INSTANCIAAPLICACION_ERROR_ACTUALIZAR = "SEGURIDAD-INSTANCIAAPLICACION-ERROR-ACTUALIZAR";
    public const string SEGURIDAD_INSTANCIAAPLICACION_ERROR_ELIMINAR = "SEGURIDAD-INSTANCIAAPLICACION-ERROR-ELIMINAR";

    public const string SEGURIDAD_ROL_NO_ENCONTRADA = "SEGURIDAD-ROL-NO-ENCONTRADA";
    public const string SEGURIDAD_ROL_ID_PAYLOAD_NO_INGRESADO = "SEGURIDAD-ROL-ID-PAYLOAD-NO-INGRESADO";
    public const string SEGURIDAD_ROL_ID_NO_INGRESADO = "SEGURIDAD-ROL-ID-NO-INGRESADO";
    public const string SEGURIDAD_ROL_ERROR_ACTUALIZAR = "SEGURIDAD-ROL-ERROR-ACTUALIZAR";
    public const string SEGURIDAD_ROL_ERROR_ELIMINAR = "SEGURIDAD-ROL-ERROR-ELIMINAR";


    public const string SEGURIDAD_USUARIOGRUPO_NO_ENCONTRADA = "SEGURIDAD-USUARIOGRUPOL-NO-ENCONTRADA";
    public const string SEGURIDAD_USUARIOGRUPO_ID_PAYLOAD_NO_INGRESADO = "SEGURIDAD-USUARIOGRUPO-ID-PAYLOAD-NO-INGRESADO";
    public const string SEGURIDAD_USUARIOGRUPO_ID_NO_INGRESADO = "SEGURIDAD-USUARIOGRUPO-ID-NO-INGRESADO";
    public const string SEGURIDAD_USUARIOGRUPO_ERROR_ACTUALIZAR = "SEGURIDAD-USUARIOGRUPO-ERROR-ACTUALIZAR";
    public const string SEGURIDAD_USUARIOGRUPO_ERROR_ELIMINAR = "SEGURIDAD-USUARIOGRUPO-ERROR-ELIMINAR";
}
