namespace aplicaciones.services;

public class CodigosError
{


    #region Códigos Error de Servicios
    //CODIGO GENERALES - ERROR
    public const string APPLICACION_ERROR_DESCONOCIDO = "APPLICACION-ERROR-DESCONOCIDO";
    public const string APPLICACION_DATOS_NO_VALIDOS = "APPLICACION-DATOS-NO-VALIDOS";

    //CODIGOS aplicacion
    public const string APPLICACION_NO_ENCONTRADA = "APPLICACION-NO-ENCONTRADA";
    public const string APPLICACION_ID_PAYLOAD_NO_INGRESADO = "APPLICACION-ID-PAYLOAD-NO-INGRESADO";
    public const string APPLICACION_ID_NO_INGRESADO = "APPLICACION-APP-ID-NO-INGRESADO";

    //CODIGOS consentimiento
    public const string CONSEN_NO_ENCONTRADO = "APPLICACION-CONSENTIMIENTO-NO-ENCONTRADO";
    public const string CONSEN_ID_PAYLOAD_NO_INGRESADO = "APPLICACION-CONSENTIMIENTO-ID-PAYLOAD-NO-INGRESADO";
    public const string CONSEN_ID_NO_INGRESADO = "APPLICACION-CONSENTIMIENTO-APP-ID-NO-INGRESADO";

    //CODIGOS EntidadInvitacion
    public const string ENTIDADINVITACION_NO_ENCONTRADO = "APPLICACION-ENTIDADINVITACION-NO-ENCONTRADO";
    public const string ENTIDADINVITACION_ID_PAYLOAD_NO_INGRESADO = "APPLICACION-ENTIDADINVITACION-ID-PAYLOAD-NO-INGRESADO";
    public const string ENTIDADINVITACION_ID_NO_INGRESADO = "APPLICACION-ENTIDADINVITACION-APP-ID-NO-INGRESADO";
    public const string ENTIDADINVITACION_ACCION_PROHIBIDA_NO_PERMISOS = "APPLICACION-ENTIDADINVITACION-ACCION-PROHIBIDA-NO-PERMISOS";
    public const string ENTIDADINVITACION_ENVIO_EMAIL_FALLIDO = "ENTIDADINVITACION-ENVIO-EMAIL-FALLIDO";

    //CODIGOS EntidadLogoAplicacion
    public const string LOGOAPLICACION_NO_ENCONTRADO = "APPLICACION-LOGOAPLICACION-NO-ENCONTRADO";
    public const string LOGOAPLICACION_ID_PAYLOAD_NO_INGRESADO = "APPLICACION-LOGOAPLICACION-ID-PAYLOAD-NO-INGRESADO";
    public const string LOGOAPLICACION_ID_NO_INGRESADO = "APPLICACION-LOGOAPLICACION-APP-ID-NO-INGRESADO";

    //CODIGOS EntidadPlantillaInvitacion
    public const string PLANTILLAINVITACION_NO_ENCONTRADO = "APPLICACION-ENTIDADPLANTILLAINVITACION-NO-ENCONTRADO";
    public const string PLANTILLAINVITACION_ID_PAYLOAD_NO_INGRESADO = "APPLICACION-ENTIDADPLANTILLAINVITACION-ID-PAYLOAD-NO-INGRESADO";
    public const string PLANTILLAINVITACION_ID_NO_INGRESADO = "APPLICACION-ENTIDADPLANTILLAINVITACION-APP-ID-NO-INGRESADO";
    #endregion


    #region Códigos Error de Controllers

    //INVITACIONCONTROLLER
    public const string INVITACIONCONTROLLER_ERROR_OBTECION_INVITACION = "APPLICACION-INVITACIONCONTROLLER-ERROR-OBTENCION-INVITACION";
    public const string INVITACIONCONTROLLER_CONTRASENA_NO_VALIDA = "APPLICACION-INVITACIONCONTROLLER-CONTRASENA-NO-VALIDA";
    public const string INVITACIONCONTROLLER_ERROR_INVITACION_NO_ENVIADA = "APPLICACION-INVITACIONCONTROLLER-INVITACION-NO-ENVIADA";
    public const string INVITACIONCONTROLLER_ERROR_CREACION_USUARIO = "APPLICACION-INVITACIONCONTROLLER-ERROR-CREACION-USUARIO";

    //USUARIOCONTROLLER
    public const string USUARIOCONTROLLER_EMAIL_NO_VALIDO = "APPLICACION-USUARIOCONTROLLER_EMAIL_NO_VALIDO";
    #endregion

}
