namespace aprendizaje.services;

public class CodigosError
{
    #region Códigos Error de Servicios
    //CODIGO GENERALES - ERROR
    public const string APRENDIZAJE_ERROR_DESCONOCIDO = "APRENDIZAJE-ERROR-DESCONOCIDO";
    public const string APRENDIZAJE_DATOS_NO_VALIDOS = "APRENDIZAJE-DATOS-NO-VALIDOS";

    //CODIGO ERROR - CURSO
    public const string APRENDIZAJE_CURSO_NO_ENCONTRADA = "APRENDIZAJE-CURSO-NO-ENCONTRADA";
    public const string APRENDIZAJE_CURSO_ID_PAYLOAD_NO_INGRESADO = "APRENDIZAJE-CURSO-ID-PAYLOAD-NO-INGRESADO";
    public const string APRENDIZAJE_CURSO_ID_NO_INGRESADO = "APRENDIZAJE-CURSO-ID-NO-INGRESADO";

    //CODIGO ERROR - GALERIA
    public const string APRENDIZAJE_GALERIA_NO_ENCONTRADA = "APRENDIZAJE-GALERIA-NO-ENCONTRADA";
    public const string APRENDIZAJE_GALERIA_ID_PAYLOAD_NO_INGRESADO = "APRENDIZAJE-GALERIA-ID-PAYLOAD-NO-INGRESADO";
    public const string APRENDIZAJE_GALERIA_ID_NO_INGRESADO = "APRENDIZAJE-GALERIA-ID-NO-INGRESADO";
    //CODIGO ERROR - TEMAGALERIA HIJO DE GALERIA
    public const string APRENDIZAJE_TEMAGALERIA_NO_ENCONTRADA = "APRENDIZAJE-TEMAGALERIA-NO-ENCONTRADA";
    public const string APRENDIZAJE_TEMAGALERIA_ID_PAYLOAD_NO_INGRESADO = "APRENDIZAJE-TEMAGALERIA-ID-PAYLOAD-NO-INGRESADO";
    public const string APRENDIZAJE_TEMAGALERIA_ID_NO_INGRESADO = "APRENDIZAJE-TEMAGALERIA-ID-NO-INGRESADO";
    public const string APRENDIZAJE_TEMAGALERIA_ERROR_ACTUALIZAR = "APRENDIZAJE-TEMAGALERIA-ERROR-ACTUALIZAR";
    public const string APRENDIZAJE_TEMAGALERIA_ERROR_ELIMINAR = "APRENDIZAJE-TEMAGALERIA-ERROR-ELIMINAR";

    //CODIGO ERROR - NEURONA
    public const string APRENDIZAJE_NEURONA_NO_ENCONTRADA = "APRENDIZAJE-NEURONA-NO-ENCONTRADA";
    public const string APRENDIZAJE_NEURONA_ID_PAYLOAD_NO_INGRESADO = "APRENDIZAJE-NEURONA-ID-PAYLOAD-NO-INGRESADO";
    public const string APRENDIZAJE_NEURONA_ID_NO_INGRESADO = "APRENDIZAJE-NEURONA-ID-NO-INGRESADO";

    //codigo error - Plan
    public const string APRENDIZAJE_PLAN_NO_ENCONTRADA = "APRENDIZAJE-PLAN-NO-ENCONTRADA";
    public const string APRENDIZAJE_PLAN_ID_PAYLOAD_NO_INGRESADO = "APRENDIZAJE-PLAN-ID-PAYLOAD-NO-INGRESADO";
    public const string APRENDIZAJE_PLAN_ID_NO_INGRESADO = "APRENDIZAJE-PLAN-ID-NO-INGRESADO";

    //CODIGO error - Temario
    public const string APRENDIZAJE_TEMARIO_NO_ENCONTRADA = "APRENDIZAJE-TEMARIO-NO-ENCONTRADA";
    public const string APRENDIZAJE_TEMARIO_ID_PAYLOAD_NO_INGRESADO = "APRENDIZAJE-TEMARIO-ID-PAYLOAD-NO-INGRESADO";
    public const string APRENDIZAJE_TEMARIO_ID_NO_INGRESADO = "APRENDIZAJE-TEMARIO-ID-NO-INGRESADO";


    #endregion


}
