namespace aprendizaje.services;

public class CodigosError
{
    #region Códigos Error de Servicios
    //CODIGO GENERALES - ERROR
    public const string APRENDIZAJE_ERROR_DESCONOCIDO = "APRENDIZAJE-ERROR-DESCONOCIDO";
    public const string APRENDIZAJE_DATOS_NO_VALIDOS = "APRENDIZAJE-DATOS-NO-VALIDOS";

    //CODIGO ERROR - GALERIA
    public const string APRENDIZAJE_GALERIA_NO_ENCONTRADA = "APRENDIZAJE-GALERIA-NO-ENCONTRADA";
    public const string APRENDIZAJE_GALERIA_ID_PAYLOAD_NO_INGRESADO = "APRENDIZAJE-GALERIA-ID-PAYLOAD-NO-INGRESADO";
    public const string APRENDIZAJE_GALERIA_ID_NO_INGRESADO = "APRENDIZAJE-GALERIA-ID-NO-INGRESADO";
    //CODIGO ERROR - TEMAGALERIA HIJO DE GALERIA
    public const string APRENDIZAJE_TEMAGALERIA_NO_ENCONTRADA = "APRENDIZAJE-TEMAGALERIA-NO-ENCONTRADA";
    public const string APRENDIZAJE_TEMAGALERIA_ID_PAYLOAD_NO_INGRESADO = "APRENDIZAJE-TEMAGALERIA-ID-PAYLOAD-NO-INGRESADO";
    public const string APRENDIZAJE_TEMAGALERIA_ID_NO_INGRESADO = "APRENDIZAJE-TEMAGALERIA-ID-NO-INGRESADO";
    public const string APRENDIZAJE_TEMAGALERIA_ERROR_ACTUALIZAR = "APRENDIZAJE-TEMAGALERIA-ERROR-ACTUALIZAR";
    public const string APRENDIZAJE_TEMAGALERIA_ERROR_ELIMINAR = "APRENDIZAJE-TEMAGALERIA-ERROR-ELIMINAR";

    //CODIGO ERROR - NEURONA
    public const string APRENDIZAJE_NEURONA_NO_ENCONTRADA = "APRENDIZAJE-NEURONA-NO-ENCONTRADA";
    public const string APRENDIZAJE_NEURONA_ID_PAYLOAD_NO_INGRESADO = "APRENDIZAJE-NEURONA-ID-PAYLOAD-NO-INGRESADO";
    public const string APRENDIZAJE_NEURONA_ID_NO_INGRESADO = "APRENDIZAJE-NEURONA-ID-NO-INGRESADO";
    public const string APRENDIZAJE_NEURONA_EXISTENTE = "APRENDIZAJE-NEURONA-EXISTENTE";

    //CODIGO ERROR - FLASHCARD HIJO DE NEURONA
    public const string APRENDIZAJE_FLASHCARDNEURONA_NO_ENCONTRADA = "APRENDIZAJE-FLASHCARD-NO-ENCONTRADA";
    public const string APRENDIZAJE_FLASHCARDNEURONA_ID_PAYLOAD_NO_INGRESADO = "APRENDIZAJE-FLASHCARD-ID-PAYLOAD-NO-INGRESADO";
    public const string APRENDIZAJE_FLASHCARDNEURONA_ID_NO_INGRESADO = "APRENDIZAJE-FLASHCARD-ID-NO-INGRESADO";
    public const string APRENDIZAJE_FLASHCARDNEURONA_ERROR_ACTUALIZAR = "APRENDIZAJE-FLASHCARD-ERROR-ACTUALIZAR";
    public const string APRENDIZAJE_FLASHCARDNEURONA_ERROR_ELIMINAR = "APRENDIZAJE-FLASHCARD-ERROR-ELIMINAR";
    public const string APRENDIZAJE_FLASHCARDNEURONA_ERROR_INSERTAR = "APRENDIZAJE-FLASHCARD-ERROR-INSERTAR";
    //FLASHCARD - FluentStorage
    public const string APRENDIZAJE_SERVICIO_ALMACENAMIENTO_NEURONA_NOEXISTE_STORAGE = "APRENDIZAJE-SERVICIO-ALMACENAMIENTO-NEURONA-STORAGE-NOENCONTRADO";
    public const string APRENDIZAJE_SERVICIO_ALMACENAMIENTO_NEURONA_FLASHCARD_NOENCONTRADO = "APRENDIZAJE-SERVICIO-ALMACENAMIENTO-NEURONA-FLASHCARD-NOENCONTRADO";
    public const string APRENDIZAJE_SERVICIO_ALMACENAMIENTO_NEURONA_FLASHCARD_ENCONTRADO = "APRENDIZAJE-SERVICIO-ALMACENAMIENTO-NEURONA-FLASHCARD-ENCONTRADO";
    #endregion


}
