namespace productos.services;

public class CodigosError
{


    #region Códigos Error de Servicios
    //CODIGO GENERALES - ERROR
    public const string PRODUCTOS_ERROR_DESCONOCIDO = "PRODUCTOS-ERROR-DESCONOCIDO";
    public const string PRODUCTOS_DATOS_NO_VALIDOS = "PRODUCTOS-DATOS-NO-VALIDOS";
    public const string PRODUCTOS_SIN_INTERPRETE_CONSULTA = "PRODUCTOS-SIN_INTERPRETE_CONSULTA";
    public const string PRODUCTOS_NO_HAY_INTERPRETE_CONSULTA = "PRODUCTOS-NO-HAY-INTERPRETE-CONSULTA";

    //CODIGO DOMINIO - SERVICIO DOMINIO [N1]
    public const string PRODUCTOS_CATEGORIA_NO_ENCONTRADA = "PRODUCTOS-CATEGORIA-NO-ENCONTRADA";
    public const string PRODUCTOS_CATEGORIA_ID_PAYLOAD_NO_INGRESADO = "PRODUCTOS-CATEGORIA-ID-PAYLOAD-NO-INGRESADO";
    public const string PRODUCTOS_CATEGORIA_ID_NO_INGRESADO = "PRODUCTOS-CATEGORIA-ID-NO-INGRESADO";
    public const string PRODUCTOS_CATEGORIA_ERROR_ELIMINAR_CATEGORIA_TIENE_HIJOS = "PRODUCTOS-CATEGORIA-ERROR-ELIMINAR-CATEGORIA-TIENE-HIJOS";
    #endregion


    #region Códigos Error de Controllers


    #endregion

}
