namespace controlescolar.servicios;

public class CodigosError
{
    public const string CONTROLESCOLAR_ERROR_DESCONOCIDO = "CONTROLESCOLAR-ERROR-DESCONOCIDO-ERROR-DESCONOCIDO";
    public const string CONTROLESCOLAR_DATOS_NO_VALIDOS = "CONTROLESCOLAR-ERROR-DESCONOCIDO-DATOS-NO-VALIDOS";
    public const string CONTROLESCOLAR_REPOSITORIO_SIN_ENTIDADES = "CONTROESCOLAR-REPOSITORIO_SIN_ENTIDADES";

    public const string CONTROLESCOLAR_ENTIDADALUMNO_NO_ENCONTRADA = "CONTROLESCOLAR-ENTIDADALUMNO-NO-ENCONTRADA";
    public const string CONTROLESCOLAR_ENTIDADALUMNO_ID_PAYLOAD_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADALUMNO-ID-PAYLOAD-NO-INGRESADO";
    public const string CONTROLESCOLAR_ENTIDADALUMNO_ID_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADALUMNO-ID-NO-INGRESADO";

    public const string CONTROLESCOLAR_ENTIDADCAMPUS_NO_ENCONTRADA = "CONTROLESCOLAR-ENTIDADCAMPUS-NO-ENCONTRADA";
    public const string CONTROLESCOLAR_ENTIDADCAMPUS_ID_PAYLOAD_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADCAMPUS-ID-PAYLOAD-NO-INGRESADO";
    public const string CONTROLESCOLAR_ENTIDADCAMPUS_ID_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADCAMPUS-ID-NO-INGRESADO";
    public const string CONTROLESCOLAR_ENTIDADCAMPUS_ACCION_PROHIBIDA_NO_PERMISOS = "CONTROLESCOLAR-ENTIDADCAMPUS-ACCION-PROHIBIDA-NO-PERMISOS";

    public const string CONTROLESCOLAR_ENTIDADINSTRUCTOR_NO_ENCONTRADA = "CONTROLESCOLAR-ENTIDADINSTRUCTOR-NO-ENCONTRADA";
    public const string CONTROLESCOLAR_ENTIDADINSTRUCTOR_ID_PAYLOAD_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADINSTRUCTOR-ID-PAYLOAD-NO-INGRESADO";
    public const string CONTROLESCOLAR_ENTIDADINSTRUCTOR_ID_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADINSTRUCTOR-ID-NO-INGRESADO";


    public const string CONTROLESCOLAR_ENTIDADESCUELA_NO_ENCONTRADA = "CONTROLESCOLAR-ENTIDADESCUELA-NO-ENCONTRADA";
    public const string CONTROLESCOLAR_ENTIDADESCUELA_ID_PAYLOAD_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADESCUELA-ID-PAYLOAD-NO-INGRESADO";
    public const string CONTROLESCOLAR_ENTIDADESCUELA_ID_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADESCUELA-ID-NO-INGRESADO";

    public const string CONTROLESCOLAR_ENTIDADPLANTEL_NO_ENCONTRADA = "CONTROLESCOLAR-ENTIDADPLANTEL-NO-ENCONTRADA";
    public const string CONTROLESCOLAR_ENTIDADPLANTEL_ID_PAYLOAD_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADPLANTEL-ID-PAYLOAD-NO-INGRESADO";
    public const string CONTROLESCOLAR_ENTIDADPLANTEL_ID_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADPLANTEL-ID-NO-INGRESADO";
    public const string CONTROLESCOLAR_ENTIDADPLANTEL_ERROR_ACTUALIZAR = "CONTROLESCOLAR-ENTIDADPLANTEL-ERROR-ACTUALIZAR";
    public const string CONTROLESCOLAR_ENTIDADPLANTEL_ERROR_ELIMINAR = "CONTROLESCOLAR-ENTIDADPLANTEL-ERROR-ELIMINAR";

    public const string CONTROLESCOLAR_ENTIDADROLPERSONAESCUELA_NO_ENCONTRADA = "CONTROLESCOLAR-ENTIDADROLPERSONAESCUELA-NO-ENCONTRADA";
    public const string CONTROLESCOLAR_ENTIDADROLPERSONAESCUELA_ID_PAYLOAD_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADROLPERSONAESCUELA-ID-PAYLOAD-NO-INGRESADO";
    public const string CONTROLESCOLAR_ENTIDADROLPERSONAESCUELA_ID_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADROLPERSONAESCUELA-ID-NO-INGRESADO";
    public const string CONTROLESCOLAR_ENTIDADROLPERSONAESCUELA_ERROR_ACTUALIZAR = "CONTROLESCOLAR-ENTIDADROLPERSONAESCUELA-ERROR-ACTUALIZAR";
    public const string CONTROLESCOLAR_ENTIDADROLPERSONAESCUELA_ERROR_ELIMINAR = "CONTROLESCOLAR-ENTIDADROLPERSONAESCUELA-ERROR-ELIMINAR";

    public const string CONTROLESCOLAR_ENTIDADEXPEDIENTE_NO_ENCONTRADA = "CONTROLESCOLAR-ENTIDADEXPEDIENTE-NO-ENCONTRADA";
    public const string CONTROLESCOLAR_ENTIDADEXPEDIENTE_ID_PAYLOAD_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADEXPEDIENTE-ID-PAYLOAD-NO-INGRESADO";
    public const string CONTROLESCOLAR_ENTIDADEXPEDIENTE_ID_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADEXPEDIENTE-ID-NO-INGRESADO";
    public const string CONTROLESCOLAR_ENTIDADEXPEDIENTE_ERROR_ACTUALIZAR = "CONTROLESCOLAR-ENTIDADEXPEDIENTE-ERROR-ACTUALIZAR";
    public const string CONTROLESCOLAR_ENTIDADEXPEDIENTE_ERROR_ELIMINAR = "CONTROLESCOLAR-ENTIDADEXPEDIENTE-ERROR-ELIMINAR";

    public const string CONTROLESCOLAR_CONFIGURACIONESCUELA_NO_ENCONTRADA = "CONTROLESCOLAR-CONFIGURACIONESCUELA-NO-ENCONTRADA";
    public const string CONTROLESCOLAR_CONFIGURACIONESCUELA_ID_PAYLOAD_NO_INGRESADO = "CONTROLESCOLAR-CONFIGURACIONESCUELA-ID-PAYLOAD-NO-INGRESADO";
    public const string CONTROLESCOLAR_CONFIGURACIONESCUELA_ID_NO_INGRESADO = "CONTROLESCOLAR-CONFIGURACIONESCUELA-ID-NO-INGRESADO";
    public const string CONTROLESCOLAR_CONFIGURACIONESCUELA_ERROR_ACTUALIZAR = "CONTROLESCOLAR-CONFIGURACIONESCUELA-ERROR-ACTUALIZAR";
    public const string CONTROLESCOLAR_CONFIGURACIONESCUELA_ERROR_ELIMINAR = "CONTROLESCOLAR-CONFIGURACIONESCUELA-ERROR-ELIMINAR";


    public const string CONTROLESCOLAR_ENTIDADMOVIMIENTOROLPERSONAESCUELA_NO_ENCONTRADA = "CONTROLESCOLAR-ENTIDADMOVIMIENTOROLPERSONAESCUELA-NO-ENCONTRADA";
    public const string CONTROLESCOLAR_ENTIDADMOVIMIENTOROLPERSONAESCUELA_ID_PAYLOAD_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADMOVIMIENTOROLPERSONAESCUELA-ID-PAYLOAD-NO-INGRESADO";
    public const string CONTROLESCOLAR_ENTIDADMOVIMIENTOROLPERSONAESCUELA_ID_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADMOVIMIENTOROLPERSONAESCUELA-ID-NO-INGRESADO";
    public const string CONTROLESCOLAR_ENTIDADMOVIMIENTOROLPERSONAESCUELA_ERROR_ACTUALIZAR = "CONTROLESCOLAR-ENTIDADMOVIMIENTOROLPERSONAESCUELA-ERROR-ACTUALIZAR";
    public const string CONTROLESCOLAR_ENTIDADMOVIMIENTOROLPERSONAESCUELA_ERROR_ELIMINAR = "CONTROLESCOLAR-ENTIDADMOVIMIENTOROLPERSONAESCUELA-ERROR-ELIMINAR";


    public const string CONTROLESCOLAR_ENTIDADDOCUMENTOBASE_NO_ENCONTRADA = "CONTROLESCOLAR-ENTIDADDOCUMENTOBASE-NO-ENCONTRADA";
    public const string CONTROLESCOLAR_ENTIDADDOCUMENTOBASE_ID_PAYLOAD_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADDOCUMENTOBASE-ID-PAYLOAD-NO-INGRESADO";
    public const string CONTROLESCOLAR_ENTIDADDOCUMENTOBASE_ID_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADDOCUMENTOBASE-ID-NO-INGRESADO";
    public const string CONTROLESCOLAR_ENTIDADDOCUMENTOBASE_ERROR_ACTUALIZAR = "CONTROLESCOLAR-ENTIDADDOCUMENTOBASE-ERROR-ACTUALIZAR";
    public const string CONTROLESCOLAR_ENTIDADDOCUMENTOBASE_ERROR_ELIMINAR = "CONTROLESCOLAR-ENTIDADDOCUMENTOBASE-ERROR-ELIMINAR";

}
