namespace controlescolar.servicios;

public class CodigosError
{
    public const string CONTROLESCOLAR_ERROR_DESCONOCIDO = "CONTROLESCOLAR-ERROR-DESCONOCIDO-ERROR-DESCONOCIDO";
    public const string CONTROLESCOLAR_DATOS_NO_VALIDOS = "CONTROLESCOLAR-ERROR-DESCONOCIDO-DATOS-NO-VALIDOS";

    public const string CONTROLESCOLAR_ENTIDADALUMNO_NO_ENCONTRADA = "CONTROLESCOLAR-ENTIDADALUMNO-NO-ENCONTRADA";
    public const string CONTROLESCOLAR_ENTIDADALUMNO_ID_PAYLOAD_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADALUMNO-ID-PAYLOAD-NO-INGRESADO";
    public const string CONTROLESCOLAR_ENTIDADALUMNO_ID_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADALUMNO-ID-NO-INGRESADO";

    public const string CONTROLESCOLAR_ENTIDADCAMPUS_NO_ENCONTRADA = "CONTROLESCOLAR-ENTIDADCAMPUS-NO-ENCONTRADA";
    public const string CONTROLESCOLAR_ENTIDADCAMPUS_ID_PAYLOAD_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADCAMPUS-ID-PAYLOAD-NO-INGRESADO";
    public const string CONTROLESCOLAR_ENTIDADCAMPUS_ID_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADCAMPUS-ID-NO-INGRESADO";
    public const string CONTROLESCOLAR_ENTIDADCAMPUS_ACCION_PROHIBIDA_NO_PERMISOS = "CONTROLESCOLAR-ENTIDADCAMPUS-ACCION-PROHIBIDA-NO-PERMISOS";

    public const string CONTROLESCOLAR_ENTIDADINSTRUCTOR_NO_ENCONTRADA = "CONTROLESCOLAR-ENTIDADINSTRUCTOR-NO-ENCONTRADA";
    public const string CONTROLESCOLAR_ENTIDADINSTRUCTOR_ID_PAYLOAD_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADINSTRUCTOR-ID-PAYLOAD-NO-INGRESADO";
    public const string CONTROLESCOLAR_ENTIDADINSTRUCTOR_ID_NO_INGRESADO = "CONTROLESCOLAR-ENTIDADINSTRUCTOR-ID-NO-INGRESADO";
}
