namespace comunicaciones.servicios;
public class CodigosError
{
    public const string COMUNICACIONES_ERROR_DESCONOCIDO = "COMUNICACIONES-ERROR-DESCONOCIDO-ERROR-DESCONOCIDO";
    public const string COMUNICACIONES_DATOS_NO_VALIDOS = "COMUNICACIONES-ERROR-DESCONOCIDO-DATOS-NO-VALIDOS";

    public const string COMUNICACIONES_EMAIL_ERROR_ENVIO = "COMUNICACIONES-EMAIL-ERROR-ENVIO";
    public const string COMUNICACIONES_WHATSAPP_ERROR_ENVIO_MENSAJE = "COMUNICACIONES-WHATSAPP-ERROR-ENVIO-MENSAJE";
    public const string COMUNICACIONES_WHATSAPP_ERROR_ENVIO_MENSAJE_IMG = "COMUNICACIONES-WHATSAPP-ERROR-ENVIO-MENSAJE_IMAGEN";
}
