namespace identidad.api;

public class CodigosErrores
{
    //CODIGOS ERROR - ACCOUNTCONTROLLER
    public const string ACCOUNTCONTROLLER_CUENTA_INEXISTENTE = "ACCOUNTCONTROLLER_CUENTA_INEXISTENTE";

    public const string ACCOUNTCONTROLLER_CUENTA_EXISTENTE = "ACCOUNTCONTROLLER_CUENTA_EXISTENTE";
    public const string ACCOUNTCONTROLLER_ERROR_DESCONOCIDO = "ACCOUNTCONTROLLER-ERROR-DESCONOCIDO-ERROR-DESCONOCIDO";
    public const string ACCOUNTCONTROLLER_ERROR_USUARIO_NOVALIDO = "ACCOUNTCONTROLLER-ERROR-USUARIO-NOVALIDO";
    public const string ACCOUNTCONTROLLER_NO_EXISTE_USUARIOID = "ACCOUNTCONTROLLER-NO-EXISTE-USUARIOID";

    //CODIGOS ERROR - AuthorizationController
    public const string AUTHORIZATIONCONTROLLER_CLIENTE_NO_LOCALIZADO = "AUTHORIZATIONCONTROLLER-CLIENTE-NO-LOCALIZADO";

    public const string AUTHORIZATIONCONTROLLER_USERNAME_PASSWORD_NOVALIDOS = "AUTHORIZATIONCONTROLLER-USERNAME-PASSWORD-NOVALIDOS";
    public const string AUTHORIZATIONCONTROLLER_TOKEN_REFRESCO_NOVALIDO = "AUTHORIZATION-TOKEN-RESFRESCO-NOVALIDO";
    public const string AUTHORIZATIONCONTROLLER_USUARIO_NOPUEDE_INICIAR_SESION = "AUTHORIZATIONCONTROLLER-USUARIO-NOPUEDE-INICIAR-SESION";
    public const string AUTHORIZATIONCONTROLLER_GRAND_TYPE_ESPECIFICADO_NOESTA_IMPLEMENTADO = "AUTHORIZATIONCONTROLLER-GRAND-TYPE-ESPECIFICADO-NOESTA-IMPLEMENTADO";
    public const string AUTHORIZATIONCONTROLLER_ASSERTION_NOVALIDO = "AUTHORIZATIONCONTROLLER_ASSERTION_NOVALIDO";
}