using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace espaciotrabajo.services;

public class CodigosError
{
    public const string ESPACIOTRABAJO_DATOS_NO_VALIDOS = "ESPACIOTRABAJO-DATOS-NO-VALIDOS";
    public const string ESPACIOTRABAJO_ERROR_DESCONOCIDO = "ESPACIOTRABAJO-ERROR-DESCONOCIDO";




    //Codigo error - EspacioTrabajo
    public const string ESPACIOTRABAJO_NO_ENCONTRADA = "ESPACIOTRABAJO-NO-ENCONTRADA";
    public const string ESPACIOTRABAJO_ID_PAYLOAD_NO_INGRESADO = "ESPACIOTRABAJO-ID-PAYLOAD-NO-INGRESADO";
    public const string ESPACIOTRABAJO_ID_NO_INGRESADO = "ESPACIOTRABAJO-ID-NO-INGRESADO";
    public const string ESPACIOTRABAJO_NO_EXISTEN_ESPACIOSTRABAJO = "ESPACIOTRABAJO-NO-EXISTEN-ESPACIOSTRABAJO";
    public const string ESPACIOTRABAJO_MIEMBRO_NO_PERTENECE_A_NINGUN_ESPACIOTRABAJO = "ESPACIOTRABAJO-MIEMBRO-NO-PERTENECE-A-NINGUN-ESPACIOTRABAJO";


    //Codigo error - Miembro - Hijo de EspacioTrabajo
    public const string ESPACIOTRABAJO_MIEMBRO_NO_ENCONTRADO = "ESPACIOTRABAJO-MIEMBRO-NO-ENCONTRADO";
    public const string ESPACIOTRABAJO_MIEMBRO_ID_PAYLOAD_NO_INGRESADO = "ESPACIOTRABAJO-MIEMBRO-ID-PAYLOAD-NO-INGRESADO";
    public const string ESPACIOTRABAJO_MIEMBRO_ID_NO_INGRESADO = "ESPACIOTRABAJO-MIEMBRO-ID-NO-INGRESADO";
    public const string ESPACIOTRABAJO_MIEMBRO_ERROR_ACTUALIZAR = "ESPACIOTRABAJO_MIEMBRO-ERROR-ACTUALIZAR";
    public const string ESPACIOTRABAJO_MIEMBRO_ERROR_ELIMINAR = "ESPACIOTRABAJO_MIEMBRO-ERROR-ELIMINAR";
}
