namespace conversaciones.services;
public class CodigosError
{
    public const string CONVERSACIONES_ERROR_DESCONOCIDO = "CONVERSACIONES-ERROR-DESCONOCIDO-ERROR-DESCONOCIDO";
    public const string CONVERSACIONES_DATOS_NO_VALIDOS = "CONVERSACIONES-ERROR-DESCONOCIDO-DATOS-NO-VALIDOS";

    public const string CONVERSACIONES_MENSAJE_NO_ENCONTRADA = "CONVERSACIONES-MENSAJE-NO-ENCONTRADA";
    public const string CONVERSACIONES_MENSAJE_ID_PAYLOAD_NO_INGRESADO = "CONVERSACIONES-MENSAJE-ID-PAYLOAD-NO-INGRESADO";
    public const string CONVERSACIONES_MENSAJE_ID_NO_INGRESADO = "CONVERSACIONES-MENSAJE-ID-NO-INGRESADO";
    public const string CONVERSACIONES_MENSAJE_ERROR_ENVIO_A_CONVERSACION = "CONVERSACIONES-MENSAJE-ERROR-ENVIO-A-CONVERSACION";
    public const string CONVERSACIONES_MENSAJE_ERROR_ACTUALIZAR = "CONVERSACIONES-MENSAJE-ERROR-ACTUALIZAR";
    public const string CONVERSACIONES_MENSAJE_ERROR_ELIMINAR = "CONVERSACIONES-MENSAJE-ERROR-ELIMINAR";

    public const string CONVERSACIONES_CONTENIDO_NO_ENCONTRADA = "CONVERSACIONES-CONTENIDO-NO-ENCONTRADA";
    public const string CONVERSACIONES_CONTENIDO_ID_PAYLOAD_NO_INGRESADO = "CONVERSACIONES-CONTENIDO-ID-PAYLOAD-NO-INGRESADO";
    public const string CONVERSACIONES_CONTENIDO_ID_NO_INGRESADO = "CONVERSACIONES-CONTENIDO-ID-NO-INGRESADO";
    public const string CONVERSACIONES_CONTENIDO_ERROR_ENVIO_A_CONVERSACION = "CONVERSACIONES-CONTENIDO-ERROR-ENVIO-A-CONVERSACION";
    public const string CONVERSACIONES_CONTENIDO_ERROR_ACTUALIZAR = "CONVERSACIONES-CONTENIDO-ERROR-ACTUALIZAR";
    public const string CONVERSACIONES_CONTENIDO_ERROR_ELIMINAR = "CONVERSACIONES-CONTENIDO-ERROR-ELIMINAR";


}
