namespace organizacion.services;

public class CodigosError
{


    #region Códigos Error de Servicios
    //CODIGO GENERALES - ERROR
    public const string ORGANIZACION_ERROR_DESCONOCIDO = "ORGANIZACION-ERROR-DESCONOCIDO";
    public const string ORGANIZACION_DATOS_NO_VALIDOS = "ORGANIZACION-DATOS-NO-VALIDOS";
    public const string ORGANIZACION_SIN_INTERPRETE_CONSULTA = "ORGANIZACION-SIN_INTERPRETE_CONSULTA";
    public const string ORGANIZACION_NO_HAY_INTERPRETE_CONSULTA = "ORGANIZACION-NO-HAY-INTERPRETE-CONSULTA";


    //CODIGO DOMINIO - SERVICIO DOMINIO [N1]
    public const string ORGANIZACION_DOMINIO_NO_ENCONTRADA = "ORGANIZACION-DOMINIO-NO-ENCONTRADA";
    public const string ORGANIZACION_DOMINIO_ID_PAYLOAD_NO_INGRESADO = "ORGANIZACION-DOMINIO-ID-PAYLOAD-NO-INGRESADO";
    public const string ORGANIZACION_DOMINIO_ID_NO_INGRESADO = "ORGANIZACION-DOMINIO-ID-NO-INGRESADO";
    //CODIGO DOMINIO - HIJO - SERVICIO UNIDADORGANIZACIONAL [N2]
    public const string ORGANIZACION_UNIDADORGANIZACIONAL_NO_ENCONTRADO = "ORGANIZACION-UNIDADORGANIZACIONAL-NO-ENCONTRADO";
    public const string ORGANIZACION_UNIDADORGANIZACIONAL_ID_PAYLOAD_NO_INGRESADO = "ORGANIZACION-UNIDADORGANIZACIONL-ID-PAYLOAD-NO-INGRESADO";
    public const string ORGANIZACION_UNIDADORGANIZACIONAL_ID_NO_INGRESADO = "ORGANIZACION-UNIDADORGANIZACIONAL-ID-NO-INGRESADO";
    public const string ORGANIZACION_UNIDADORGANIZACIONAL_ERROR_ACTUALIZAR = "ORGANIZACION-UNIDADORGANIZACIONAL-ERROR-ACTUALIZAR";
    public const string ORGANIZACION_UNIDADORGANIZACIONAL_ERROR_ELIMINAR = "ORGANIZACION-UNIDADORGANIZAIONAL-ERROR-ELIMINAR";
    //CODIGO DOMINIO - HIJO - SERVICIO USUARIODOMINIO [N2]
    public const string ORGANIZACION_USUARIODOMINIO_NO_ENCONTRADO = "ORGANIZACION-USUARIODOMINIO-NO-ENCONTRADO";
    public const string ORGANIZACION_USUARIODOMINIO_EXISTENTE = "ORGANIZACION-USUARIODOMINIO-EXISTENTE";
    public const string ORGANIZACION_USUARIODOMINIO_EXISTENTE_EN_LISTA = "ORGANIZACION-USUARIODOMINIO-DOMINIO-EN-LISTA";
    public const string ORGANIZACION_USUARIODOMINIO_ID_PAYLOAD_NO_INGRESADO = "ORGANIZACION-USUARIODOMINIO-ID-PAYLOAD-NO-INGRESADO";
    public const string ORGANIZACION_USUARIODOMINIO_ID_NO_INGRESADO = "ORGANIZACION-USUARIODOMINIO-ID-NO-INGRESADO";
    public const string ORGANIZACION_USUARIODOMINIO_ERROR_ACTUALIZAR = "ORGANIZACION-USUARIODOMINIO-ERROR-ACTUALIZAR";
    public const string ORGANIZACION_USUARIODOMINIO_ERROR_ELIMINAR = "ORGANIZACION-USUARIODOMINIO-ERROR-ELIMINAR";
    public const string ORGANIZACION_USUARIODOMINIO_ACCION_NO_IMPLEMENTADA = "ORGANIZACION-USUARIODOMINIO-ACCION_NO_IMPLEMENTADA";
    //CODIGO DOMINIO - NIETO - SERVICIO ELEMENTOOU[N2]
    public const string ORGANIZACION_ELEMENTOOU_NO_ENCONTRADO = "ORGANIZACION-ELEMENTOOU-NO-ENCONTRADO";
    public const string ORGANIZACION_ELEMENTOOU_EXISTENTE = "ORGANIZACION-ELEMENTOOU-EXISTENTE";
    public const string ORGANIZACION_ELEMENTOOU_ID_PAYLOAD_NO_INGRESADO = "ORGANIZACION-ELEMENTOOU-ID-PAYLOAD-NO-INGRESADO";
    public const string ORGANIZACION_ELEMENTOOU_ID_NO_INGRESADO = "ORGANIZACION-ELEMENTOOU-ID-NO-INGRESADO";
    public const string ORGANIZACION_ELEMENTOOU_ERROR_ACTUALIZAR = "ORGANIZACION-ELEMENTOOU-ERROR-ACTUALIZAR";
    public const string ORGANIZACION_ELEMENTOOU_ERROR_ELIMINAR = "ORGANIZACION-ELEMENTOOU-ERROR-ELIMINAR";
    public const string ORGANIZACION_ELEMENTOOU_ACCION_NO_IMPLEMENTADA = "ORGANIZACION-ELEMENTOOU-ACCION_NO_IMPLEMENTADA";
    public const string ORGANIZACION_ELEMENTOOU_NO_EXISTE_OU_EN_DOMINIO= "ORGANIZACION-ELEMENTOOU-NO-EXISTE-OU-EN-DOMINIO";
    #endregion


    #region Códigos Error de Controllers


    #endregion

}
