namespace disenocurricular.services;

public class CodigosError
{
    #region Códigos Error de Servicios
    //CODIGO GENERALES - ERROR
    public const string DISENOCURRICULAR_ERROR_DESCONOCIDO = "DISENOCURRICULAR-ERROR-DESCONOCIDO";
    public const string DISENOCURRICULAR_DATOS_NO_VALIDOS = "DISENOCURRICULAR-DATOS-NO-VALIDOS";

    //CODIGO ERROR - CURSO
    public const string DISENOCURRICULAR_CURSO_NO_ENCONTRADA = "DISENOCURRICULAR-CURSO-NO-ENCONTRADA";
    public const string DISENOCURRICULAR_CURSO_ID_PAYLOAD_NO_INGRESADO = "DISENOCURRICULAR-CURSO-ID-PAYLOAD-NO-INGRESADO";
    public const string DISENOCURRICULAR_CURSO_ID_NO_INGRESADO = "DISENOCURRICULAR-CURSO-ID-NO-INGRESADO";

    //codigo error - Plan
    public const string DISENOCURRICULAR_PLAN_NO_ENCONTRADA = "DISENOCURRICULAR-PLAN-NO-ENCONTRADA";
    public const string DISENOCURRICULAR_PLAN_ID_PAYLOAD_NO_INGRESADO = "DISENOCURRICULAR-PLAN-ID-PAYLOAD-NO-INGRESADO";
    public const string DISENOCURRICULAR_PLAN_ID_NO_INGRESADO = "DISENOCURRICULAR-PLAN-ID-NO-INGRESADO";

    //CODIGO error - Temario
    public const string DISENOCURRICULAR_TEMARIO_NO_ENCONTRADA = "DISENOCURRICULAR-TEMARIO-NO-ENCONTRADA";
    public const string DISENOCURRICULAR_TEMARIO_ID_PAYLOAD_NO_INGRESADO = "DISENOCURRICULAR-TEMARIO-ID-PAYLOAD-NO-INGRESADO";
    public const string DISENOCURRICULAR_TEMARIO_ID_NO_INGRESADO = "DISENOCURRICULAR-TEMARIO-ID-NO-INGRESADO";


    #endregion


}

